### ISSUE TITLE
Remove necessity to manually scroll to top of page when taking a full-page screenshot

### ISSUE THREAD

**Issue by Gitoffthelawn** [M-Reimer/savescreenshot#46] opened 2021-12-25 21:02 UTC
I noticed that, when taking screenshots of entire pages that don't fit in the viewport, sometimes only the current viewport is captured.  A workaround is to remember to always scroll to the top of the page before taking the screenshot.

Could this extension be improved to handle this automatically?

**Comment by M-Reimer** [comment] 2021-12-26 10:33
Probably duplicate of #45 

I would need an example to try this, but as the Firefox built-in API does not actually need scrolling at all (it just takes a screenshot of the whole page) there is probably not much I can do here.

**Comment by Gitoffthelawn** [comment] 2021-12-26 19:50
Thanks.  When (if?) I come across a public-facing example, I'll be sure to let you know.

**Comment by M-Reimer** [comment] 2021-12-27 10:17
Thanks in advance. Please create a new Issue for this exact website in this case.

**Closed by M-Reimer** 2021-12-27 10:17 UTC
