### ISSUE TITLE
Option to increase accuracy of full-page screenshots

### ISSUE THREAD

**Issue by Gitoffthelawn** [M-Reimer/savescreenshot#66] opened 2023-12-03 21:25 UTC
I have found that some pages don't screenshot correctly with this extension that do screenshot correctly with Firefox's devtools.

The sites I have encountered this issue on require logins, and I understand that creating logins is beyond the scope of testing/debugging.

This occurs when the page contains one or more fixed-positioned elements.

However, a workaround is to manually scroll to the top of the page before taking a full-page screenshot.  This resolves the issue many times.

As such, can you add an *option* to the extension for it to scroll to the top of the page before taking a full-page screenshot?  This will increase the likelihood of accurate screenshots.  If you can scroll the page back to its current position, all the better.

(Fixing the underlying issue would be even better, but I have a hunch that is out of your hands.)

**Comment by M-Reimer** [comment] 2023-12-03 21:39
Problem is that the scrolling element is not always "body" in the HTML which makes scrolling to the top tricky if not impossible.

**Comment by Gitoffthelawn** [comment] 2023-12-04 06:38
Good point.  I'll see if simply scrolling `body` to the top, then scrolling `html` to the top will be helpful.  I think that will handle many cases.

**Comment by M-Reimer** [comment] 2023-12-04 15:19
Actually I'm not sure if this should be "fixed" at all. "Save Screenshot" saves what is currently on the website. If parts move with scrolling, then they are at the place they are currently on the website. If someone wants to screenshot this page "all the way scrolled up", then he has to scroll "all the way up" manually.

The problem I see here are issues caused by the "fix" for this issue. Scrolling in dynamic pages may change their content and so users don't get the expected screenshot. Then the next person comes around and asks for having this setting "per domain".

That's just all very much out of scope. I want to have a simple, easy, screenshot saving Add-on.

**Comment by Gitoffthelawn** [comment] 2023-12-05 04:25
I hear you.  Let's both think about it, and maybe talk more here.

The desire to "take a screenshot of what I actually see" is likely the end goal for most users.  The challenge is finding a solution that works.

As you mentioned, by scrolling, it's possible the contents could change.  On the other hand, by not scrolling, the screenshots don't always match what the user actually sees.

I'm not sure of the solution at this time.  One possibility is to have an option to let the user decide which mode will meet their needs most of the time.  But having something work on it's own would be better.  That's easier said than done, of course.

For a few sites, I have Stylus CSS styles that I overlay before taking screenshots.  But this is cumbersome and requires that I always remember to enable those styles right before taking screenshots (and then disable those styles right after taking screenshots).  It's not ideal, so I feel the better solution is within the screenshot tool itself.

It surprises (and impresses) me that the Firefox devtool screenshot function seems to always work, but your extension doesn't.  Any idea why that is the case, or how to harness its power in your extension?

**Comment by M-Reimer** [comment] 2023-12-05 15:41
> As you mentioned, by scrolling, it's possible the contents could change. On the other hand, by not scrolling, the screenshots don't always match what the user actually sees.

So far I haven't seen any example for this. If I'm halfway in a page and some kind of "header" is on top of what I'm seeing, then, at least I, am totally OK with having this header bar somewhere in the middle of my screenshot. This is what I mean with "matches what I see". And there already is an option in the settings that a full page screenshot can be taken from the current scroll position. This was initially added to allow capturing **really long** pages that exceed what Firefox allows to capture. It makes it possible to take those screenshots in two (or more) steps and merge manually in the image editor of choice. I never had a need for this as I don't use screenshots to archive websites. It is the most wasteful way of doing this, so I don't recommend it. The proper way to archive a website is to create a PDF from it.

> I'm not sure of the solution at this time. One possibility is to have an option to let the user decide which mode will meet their needs most of the time. But having something work on it's own would be better. That's easier said than done, of course.

Scrolling a website works for some but causes issues for others. So worst case users would have to regularly toggle this setting.

> For a few sites, I have Stylus CSS styles that I overlay before taking screenshots. But this is cumbersome and requires that I always remember to enable those styles right before taking screenshots (and then disable those styles right after taking screenshots). It's not ideal, so I feel the better solution is within the screenshot tool itself.

There are websites out there that totally will require CSS hacks to take full page screenshots with success. In theory it would be possible to bundle "per site" CSS styles to automatically apply them before taking the screenshot. But this only makes sense for "big websites" and I can only test websites where I don't need a login for.

> It surprises (and impresses) me that the Firefox devtool screenshot function seems to always work, but your extension doesn't. Any idea why that is the case, or how to harness its power in your extension?

I did try to dig into this, but Mozilla code is (and actually always was) difficult to read and really difficult to follow. But even if I could find the reason, there is not much that can be done about it.

The only way to take a screenshot as an Add-on is to use the one and only API endpoint. But the nice thing about this is, that the Firefox built-in "Take Screenshot" feature (context menu of websites) uses the exact same API. So it shares the same issues with my Add-on. So the correct way to deal with this is to test problematic websites with the Firefox built-in screenshot tool and if it can be reproduced, file a bug at bugzilla.mozilla.org.

**Comment by M-Reimer** [comment] 2024-03-24 13:23
Without any example page it is not possible to find any solution here.
What I do is call into an API, provided by Mozilla, and use whatever I get back from that. I already have huge amount of special handling around that to allow several use cases, many other screenshot Add-ons did not think about.
But even if my Add-on already got way bigger than planned initially, I still want to keep it somewhat simple without too complex "niche chase" handling.

**Closed by M-Reimer** 2024-03-24 13:23 UTC
