### ISSUE TITLE
No screenshot possible for this long but not overlong webpage

### ISSUE THREAD

**Issue by pstein** [M-Reimer/savescreenshot#62] opened 2023-09-01 08:23 UTC
In Firefox v116 64bit on Windows 10 I tried to capture the following webpage:

https://www.immobiliarecittaideale.com/scheda4.asp?immID=7138

The web page is long but not overlong (< 32000 pixel rows).
So Save Screenshot should be able to handle it.

Unfortunately nothing happens when I click on the "Save screenshot" toolbar icon.
No auto-save (as usual).
No error popup.

Can you fix it?

Thats my options (see attachment)

![options save screenshot](https://github.com/M-Reimer/savescreenshot/assets/2775875/869457f8-4803-4ad8-9822-c20fde8e8bfd)

**Comment by M-Reimer** [comment] 2023-09-14 09:09
This actually is a duplicate of #57 
I added your URL to my bug report.

**Closed by M-Reimer** 2023-09-14 09:09 UTC
Labels: upstream bug
