### ISSUE TITLE
Bug: Overlong webpage not printed/saved

### ISSUE THREAD

**Issue by pstein** [M-Reimer/savescreenshot#57] opened 2023-03-13 08:30 UTC
I tried to save ("as usual") the following overlog webpage into a *.png file on my local computer

https://de.aliexpress.com/item/1005005020611782.html

After clicking on "Save Screenshot" toolbar icon in newest Firefox on Windows10 the "Save Screenshot" WebExtension recognizes 
that the webpage is overlong and announces a truncation.
I click OK....but nothing happens. I expected a truncated save.

But I did not found a truncated *.png file in my download folder even after 5 minutes.
I guess its a bug.

Plx fix.

"Save Screenshot" works before and after rthat special webpage. So its installed correctly

Thank you.

**Comment by hellsing71** [comment] 2023-03-23 11:52
I can confirm. In FF 111.0 over Win 11 having Save Screenshot 10.0.0 the plugin doesn't save the PNG file. If I try it in JPEG I get a ~32k pix high, truncated page.

**Comment by M-Reimer** [comment] 2023-04-26 14:19
Actually I did create a bug report on my own just now: https://bugzilla.mozilla.org/show_bug.cgi?id=1830085

To be honest: The list of bugs, I have to work around in my Add-ons, is getting long. Really long. And most of the bugs, I have to work around, are unfixed for years.

Not much fun to develop Add-ons for Mozilla, but basically the only choice, currently, is to use a "not so good" browser (Firefox) and a "bad" browser (Chrome). So I try to make the "not so good" browser at least "a bit better" with Add-ons... :cry:

**Comment by pstein** [comment] 2023-04-27 05:55
Hey Manual, thank you for comment.

I didn't know that the Firefox Screenshot API contains (so many) bugs.
I though your AddOn needs just a quick fix.

So don't worry. I appreciate your AddOn anyway.
Thank you for filing a bug.
Lets see what Firefox devs answer.

**Comment by pstein** [comment] 2023-05-06 11:12
Hey, looks good.
Seems to work (at least for the linked webpage above).
I will check in the next time if the problem occurs still on other webpages.
For now we could consider it as solved.

**Comment by pstein** [comment] 2023-05-14 06:51
I have encountered another webpage where Save Screenshot WebeExt cannot auto capturen full length.

Have a look at:

https://www.essentialpim.com/help/index.html?task_editing.htm

Maybe you can fix it
Thank you

**Comment by DJCrashdummy** [comment] 2023-08-04 13:12
interesting... i have got a similar issue (version 10.0.0; Firefox 102.13.0 ESR; Windows 10):
there is no warning, nothing... **but** as soon as i save a whole page - no mater if as png, jpg or via copy&paste - **every pixel** starting with line 16383 **is black**. :open_mouth:
at first i didn't even notice it, but unfortunately i can reliable reproduce it and also with the built in function via context menu (or toolbar icon). interestingly when using the dev-tools with `devtools.command-button-screenshot.enabled` set to `true`, there are no black pixels, but the screenshot simply ends after pixel 15000. :confounded:
-> so yes, **truncated screenshots do happen, but with an other internal function.**

my guess is that the issues regarding this addon and the built in function (via context menu or toolbar icon) may have something to do with HiDPI scaling, because also if the browser window is set to a certain pixel size (with various other addons), the screenshots of the webpage are bigger about that HiDPI factor (except a few pixels because of scrollbars etc.)...
- the issues described at first occoured with **150% HiDPI scaling**.
- setting HiDPI scaling to 100%, the screenshot was unfortunately only <1400 pixels long (without any issue) of course.
- **but** after setting **HiDPI scaling to 200%** it got even more interesting:
everything seemed to work fine... the screenshot was complete, was more than 27000 pixel long and had **no black pixels** at all, but **starting with the pixel line 16383** there is a weird **glitch in the background** color resp. it seems that the background is missing. :confused: 

i'm sorry i can't give you the link resp. it would be useless as it is an login protected page, but if really necessary i can add the (blurred - what would be some work) screenshot.

*BTW: this addon is by far the best website screenshot addon for any browser! usually it works really smooth and the settings are pure genius (especially the custom default name/folder) with every setting you could wish for but still as minimal as possible. thank you very much!*

**Comment by pstein** [comment] 2023-10-29 08:28
....and another sample:

https://www.immobiliarecittaideale.com/scheda4.asp?immID=7126

This page can be saved to *.png file in Chrome browser with
Awesome Screenshot WebExtension.

**Comment by M-Reimer** [comment] 2023-10-29 09:45
Please post examples here: https://bugzilla.mozilla.org/show_bug.cgi?id=1830085
I can't fix this.

**Comment by M-Reimer** [comment] 2024-03-19 21:54
@pstein Likely I just fixed your issue. So far only on GIT but will be in the next release.

**Comment by M-Reimer** [comment] 2024-03-24 13:20
All cases, discussed here, should at least result in being automatically truncated  in the upcoming release.

**Closed by M-Reimer** 2024-03-24 13:20 UTC
Labels: upstream bug
